### Compare, Pivoting & Melting

In [1]:
import pandas as pd

### Compare

In [8]:
shop_7Sep = {
    "Fruits":['Mango','Apple','Banana','Papaya'],
    "Price":[100,150,60,30],
    "Qunt":[10,8,12,14]
}
stock_7Sep = pd.DataFrame(shop_7Sep)

shop_8Sep = {
    "Fruits":['Mango','Apple','Banana','Papaya'],
    "Price":[120,200,60,35],
    "Qunt":[15,6,24,17]
}
stock_8Sep = pd.DataFrame(shop_8Sep)

#----Compare----
stock_7Sep.compare(stock_8Sep)
stock_7Sep.compare(stock_8Sep, align_axis=0)
stock_7Sep.compare(stock_8Sep, keep_shape=True)
stock_7Sep.compare(stock_8Sep, keep_equal=True)

stock_7Sep.compare(stock_8Sep, align_axis=0, keep_shape=True,keep_equal=True)

         Fruits  Price  Qunt
0 self    Mango    100    10
  other   Mango    120    15
1 self    Apple    150     8
  other   Apple    200     6
2 self   Banana     60    12
  other  Banana     60    24
3 self   Papaya     30    14
  other  Papaya     35    17

### Pivoting

In [11]:
monthly_sales = {
    "Product":['Laptop','Mobile','Laptop','Mobile','Laptop','Laptop'],
    "Month":['Jan','Jan','Feb','Feb','Mar','Mar'],
    "Price":[95000,25000,67000,12000,65000,75000],
}
sales = pd.DataFrame(monthly_sales)

#-----Pivot-----
sales.pivot_table(
    columns = "Month",
    index = "Product",
    values = "Price",
    aggfunc = "sum"
)

Month        Feb      Jan       Mar
Product
Laptop   67000.0  95000.0  140000.0
Mobile   12000.0  25000.0       NaN

### Melting

In [14]:
shop_sales = {
    "Products":['Laptop','Mobile','Mouse'],
    "Jan":[45000,14000,140],
    "Feb":[65000,25000,560],
    "Mar":[75000,23000,750]
}
sales_df = pd.DataFrame(shop_sales)
sales_df.melt(
    id_vars = "Products",
    var_name = "Month",
    value_name = "Price"
)

  Products Month  Price
0   Laptop   Jan  45000
1   Mobile   Jan  14000
2    Mouse   Jan    140
3   Laptop   Feb  65000
4   Mobile   Feb  25000
5    Mouse   Feb    560
6   Laptop   Mar  75000
7   Mobile   Mar  23000
8    Mouse   Mar    750